[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11",
    "cmake",
    "scikit-build",
]
build-backend = "setuptools.build_meta"


[tool.pytest.ini_options]
testpaths = ["tests"]